#ifndef TZBSP_ERR_FATAL_H
#define TZBSP_ERR_FATAL_H
/**
@file tzbsp_err_fatal.h
@brief Provide TZBSP error fatal enumarations
*/

/*===========================================================================
 Copyright (c) Qualcomm Technologies, Inc.
 All Rights Reserved.
 Confidential and Proprietary - Qualcomm Technologies, Inc.
===========================================================================*/

/*===========================================================================

                              DEFINES

===========================================================================*/
/** Possible reasons for the ERR_FATAL call
 *  NOTE: New entries should be added to the end, and old entries never removed.
 *        These values are used across multiple generations of TZ.
 *        Any update here requires a corresponding update to reset_reason_oem_map.c.
 */

/* TZBSP_ERR_FATAL_NONE is depricated */
#define APPS_ERR_FATAL_NON_SECURE_WDT 1
#define TZBSP_ERR_FATAL_SECURE_WDT 2
#define TZBSP_ERR_FATAL_AHB_TIMEOUT 3
#define AOP_ERR_FATAL_RPM_WDOG 4
#define AOP_RPM_ERR_FATAL 5
#define SOC_ERR_FATAL_NOC_ERROR 6
#define DDR_BIMC_ERROR_FATAL 7
#define SMEM_ERR_FATAL 8
#define ERR_FATAL_XPU_VIOLATION 9
#define SMMU_ERR_FATAL 10
#define TZBSP_ERR_FATAL_QSEE_ERR 11
#define TZBSP_ERR_FATAL_EL3_SP_EL0_SYNCH 12
#define TZBSP_ERR_FATAL_EL3_SP_EL0_IRQ 13
#define TZBSP_ERR_FATAL_EL3_SP_EL0_FIQ 14
#define TZBSP_ERR_FATAL_EL3_SP_EL0_ERR 15
#define TZBSP_ERR_FATAL_EL3_SP_EL3_SYNCH 16
#define TZBSP_ERR_FATAL_EL3_SP_EL3_IRQ 17
#define TZBSP_ERR_FATAL_EL3_SP_EL3_FIQ 18
#define TZBSP_ERR_FATAL_EL3_SP_EL3_ERR 19
#define TZBSP_ERR_FATAL_EL3_LEL64_SYNCH 20
#define TZBSP_ERR_FATAL_EL3_LEL64_IRQ 21
#define TZBSP_ERR_FATAL_EL3_LEL64_FIQ 22
#define TZBSP_ERR_FATAL_EL3_LEL64_ERR 23
#define TZBSP_ERR_FATAL_EL3_LEL32_SYNCH 24
#define TZBSP_ERR_FATAL_EL3_LEL32_IRQ 25
#define TZBSP_ERR_FATAL_EL3_LEL32_FIQ 26
#define TZBSP_ERR_FATAL_EL3_LEL32_ERR 27
#define TZBSP_ERR_FATAL_EL1_SP_EL0_SYNCH 28
#define TZBSP_ERR_FATAL_EL1_SP_EL0_IRQ 29
#define TZBSP_ERR_FATAL_EL1_SP_EL0_FIQ 30
#define TZBSP_ERR_FATAL_EL1_SP_EL0_ERR 31
#define TZBSP_ERR_FATAL_EL1_SP_EL1_SYNCH 32
#define TZBSP_ERR_FATAL_EL1_SP_EL1_IRQ 33
#define TZBSP_ERR_FATAL_EL1_SP_EL1_FIQ 34
#define TZBSP_ERR_FATAL_EL1_SP_EL1_ERR 35
#define TZBSP_ERR_FATAL_EL1_LEL64_SYNCH 36
#define TZBSP_ERR_FATAL_EL1_LEL64_IRQ 37
#define TZBSP_ERR_FATAL_EL1_LEL64_FIQ 38
#define TZBSP_ERR_FATAL_EL1_LEL64_ERR 39
#define TZBSP_ERR_FATAL_EL1_LEL32_SYNCH 40
#define TZBSP_ERR_FATAL_EL1_LEL32_IRQ 41
#define TZBSP_ERR_FATAL_EL1_LEL32_FIQ 42
#define TZBSP_ERR_FATAL_EL1_LEL32_ERR 43
#define AOP_RPM_DRIVER_ERR_FATAL 44
#define TZBSP_ERR_FATAL_RESET_TIMER_EXP 45
#define TZBSP_ERR_FATAL_ICE_ERR 46
#define TZBSP_ERR_FATAL_LMH_DRIVER_ERR 47
#define TZBSP_ERR_FATAL_ACCESS_CONTROL 48
#define TZBSP_ERR_FATAL_CLOCK 49
#define TZBSP_ERR_FATAL_GIC_CPU_MAP_INVALID 50
#define TZBSP_ERR_FATAL_SEC_WDT_TIMER_TRIGGER 51
#define TZBSP_ERR_FATAL_FAULT_DETECTED 52
#define TZBSP_ERR_FATAL_MON_PREFETCH_ABT 53
#define TZBSP_ERR_FATAL_MON_DATA_ABT 54
#define TZBSP_ERR_FATAL_QSEE_PREFETCH_ABT 55
#define TZBSP_ERR_FATAL_QSEE_DATA_ABT 56
#define TZBSP_ERR_FATAL_QSEE_UNDEF_ABT 57
#define TZBSP_ERR_FATAL_QSEE_STACK_CHK_FAILED 58
#define TZBSP_ERR_FATAL_MON_STACK_CHK_FAILED 59
#define TZBSP_ERR_FATAL_MON_ASSERT_FAILED 60
#define TZBSP_ERR_FATAL_HLOS_IMG_TAMPERED 61
#define TZBSP_ERR_FATAL_HLOS_BL_MILESTONE_FAILED 62
#define TZBSP_ERR_INIT_BOOT_TAMPER_CHECK_FAILED 63
#define TZBSP_ERR_INIT_MON_PC_INIT_FAILED 64
#define TZBSP_ERR_FATAL_MON_UNDEF 65
#define TZBSP_ERR_FATAL_COUNTER_MEASURE_FAILED 66
#define TZBSP_ERR_FATAL_HLOS_ERR_NO_RESET_INDICATION 67
#define TZBSP_ERR_FATAL_MELTDOWN_FAILURE 68
#define TZBSP_ERR_FATAL_MELTDOWN_NO_FREE_PT_MEMORY 69
#define TZBSP_ERR_FATAL_MINK_ASSERT_FAILED 70
#define TZBSP_ERR_FATAL_TINY_MODEM_BOOT_FAILED 71
#define TZBSP_ERR_FATAL_QSEE_ERR_SET 72
#define APPS_ERR_FATAL_BOOT_RESTRICT_WRONG_HLOS 73
#define TZBSP_ERR_FATAL_MALLOC_FAILED 74
#define TZBSP_ERR_FATAL_DIAG_LOG_CTX_CREATE_FAILED 75
#define TZBSP_ERR_FATAL_SEC_WDOG_BARK_INT_MASK_FAILED 76
#define TZBSP_ERR_FATAL_INIT_BOOT_TAMPER_CHECK_FAILED 77
#define TZBSP_ERR_FATAL_LK_KERNEL 78
#define SYSDBG_ERR_FATAL_IPCC 79
#define TZBSP_ERR_FATAL_SUBSYSTEM_FAILURE 80
#define SYSDBG_ERR_FATAL_DCC_INIT 81
#define CRYPTO_ERR_FATAL_LOG_ENCR_CIPHER_FREE_FAILED 82
#define TZBSP_ERR_FATAL_INVAL_SEC_MEM_RGN_ID 83
#define TZBSP_ERR_FATAL_HWKM_INIT_FAILED 84
#define TZBSP_ERR_FATAL_INCOMPAT_SW 85
#define TZBSP_ERR_FATAL_FAULTED_APP 86
#define TZBSP_ERR_FATAL_QSEE_PAUTH_FAILED 87
#define TZBSP_ERR_FATAL_MON_PAUTH_FAILED 88
#define CPUCP_ERR_FATAL_CLKDOM_INIT_FAILED 89
#define TZBSP_ERR_FATAL_VERIFY_ECC_SETTINGS_FAILED 90
#define TZBSP_APP_REGION_INITIALIZATION_FAILED 91
#define TZBSP_APP_REGION_RAM_PARTITION_UPDATE_FAILED 92
#define TZBSP_ERR_FATAL_CLIENTID_MISMATCH_ERR 93
#define TZBSP_ERR_FATAL_DARE_SEC_AUTH_ERR 94
#define TZBSP_ERR_FATAL_DARE_INIT_FAILED 95
#define TZBSP_ERR_FATAL_GIC_UNCORRECTABLE_ERR 96
#define TZBSP_ERR_FATAL_PRNG_FIPS_HYBRID_ERR 97
#define TZBSP_LCP_DARE_REG_RAM_PARTITION_UPDATE_FAILED 98
#define TZBSP_ERR_FATAL_TZ_ENTRY_MILESTONE_FAILED 99
#define TME_ERR_FATAL_TMECOM_PROTOCOL_FAILURE 100
#define TZBSP_ERR_FATAL_LPI_LB_INIT_FAILED 101
#define TZBSP_ERR_FATAL_LPI_LB_ERR 102
#define TZBSP_ERR_FATAL_MON_SB_FAILED 103
#define TZBSP_ERR_FATAL_TIMER_INIT_FAILED 104
#define TZBSP_ERR_FATAL_LCP_INIT_FAILED 105
#define TZBSP_ERR_FATAL_HYP_LOAD_PROHIBITED 106
#define TZBSP_ERR_FATAL_INVALID_BOOT_STACK 107
#define TZBSP_ERR_FATAL_INVALID_SWITCH_CALL 108
#define SYSTEM_DEBUG_ERR_FATAL 109
#define TZBSP_ERR_FATAL_DUMPTABLE_ASSIGN 110
#define TZBSP_ERR_FATAL_AC_RESTORE 111
#define TZBSP_ERR_FATAL_COPY_FROM_BB 112
#define TZBSP_ERR_FATAL_TA_THREAD_STACK 113
#define TZBSP_ERR_FATAL_VFP_INIT 114
#define TZBSP_ERR_FATAL_INVALID_CONTEXT 115
#define TZBSP_ERR_FATAL_NS_IRQ_OR_FIQ 116
#define TZBSP_ERR_FATAL_INVALID_SEC_MEM_ID 117
#define TZBSP_ERR_FATAL_VM_MEM_CPY 118
#define TZBSP_ERR_FATAL_VM_SESSION_KEY_RMVL 119
#define TZBSP_ERR_FATAL_CMN_ENTRY 120
#define TZBSP_ERR_FATAL_BUFFER_SIZE_CHECK 121
#define TZBSP_ERR_FATAL_MINK_VTOP 122
#define ECOSYSTEM_ERR_FATAL_ASSERT_FAILED 123
#define TZBSP_ERR_FATAL_EXCEPTION 124
#define TZBSP_ERR_FATAL_QB_PIMEM_WIN_CFG_FAILED 125
#define TZBSP_ERR_FATAL_MODEM_REGISTRATION_FAILED 126
#define TZBSP_ERR_FATAL_IC_CONFIG_INT_FAILED 127
#define TZBSP_ERR_FATAL_IC_SET_INT_TARGETS_FAILED 128
#define TZBSP_ERR_FATAL_QB_MODEM_RESUME_FAILED 129
#define TZBSP_ERR_FATAL_DS_REQ_FAILED 130
#define TZBSP_ERR_FATAL_UEFI_EXIT_SWFUSE_READ_FAILED 131
#define TZBSP_ERR_FATAL_TME_ERROR_FATAL 132
#define SOC_ERR_FATAL_IPCC_BIST_ERROR 133
#define CMSR_ERROR_FATAL 134
#define TZBSP_ERR_FATAL_MINK_MAP_FAILED 135
#define TZBSP_ERR_FATAL_DRTM_LAUNCH_FAILED 136
#define TZBSP_ERR_FATAL_pIMEM_COUNTER_CHECK_FAILED 137
#define TZBSP_ERR_FATAL_MILESTONE_SERVICE_FAILED 138
#define TZBSP_ERR_FATAL_CAMERA_INVALID_ACCESS_DETECTED 139
#define CPUCP_ERR_FATAL_RESET_SYNC_FAILED 140

/**
 *  NOTE: Any update in this file requires a corresponding update to
 *        reset_reason_oem_map.c to keep the files in sync.
 */

#endif /* TZBSP_ERR_FATAL_H */
